name: Create avatar release

on:
    workflow_dispatch:
        inputs:
            release-version:
                description: The release version
                default: 'v1.0'
                required: true
                type: string
            release-tag:
                description: The release tag
                default: '1.0'
                required: true
                type: string

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: yarn
            - run: yarn start
            - name: Zip ./build/
              run: cd build && zip -r ../Ccow.zip .
            - name: Release bundled zip
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: ./Cow.zip
                  release_name: ${{ inputs.release-version }}
                  tag: ${{ inputs.release-tag }}
